package Modelo;
// Generated 06/06/2020 07:59:00 PM by Hibernate Tools 3.6.0



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String tv;
     private String radio;
     private String tostadora;

    public Producto() {
    }

    public Producto(String tv, String radio, String tostadora) {
       this.tv = tv;
       this.radio = radio;
       this.tostadora = tostadora;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getTv() {
        return this.tv;
    }
    
    public void setTv(String tv) {
        this.tv = tv;
    }
    public String getRadio() {
        return this.radio;
    }
    
    public void setRadio(String radio) {
        this.radio = radio;
    }
    public String getTostadora() {
        return this.tostadora;
    }
    
    public void setTostadora(String tostadora) {
        this.tostadora = tostadora;
    }




}


